# Header

logo: /images/selimlab-logo-vector-with-text.svg

slogan: Fundamental and applied research on wide band gap materials.<br />Radiation damage studies.

menu:
  Dr. <span class="d-inline d-sm-none d-xl-inline">Farida A.</span> Selim: /
  <span class="d-inline d-sm-none d-xl-inline">Research</span> Facilities: /facilities
  Publications: /publications
  Teaching: /teaching
  Software<span class="d-inline d-sm-none d-xl-inline"> Development</span>: /software
  People: /people
  Events: /events  
  Blog: /blog

menuFooter:
  Dr. Selim: /
  Facilities: /facilities
  Publications: /publications
  Research: /research
  Teaching: /teaching
  Software: /software
  People: /people
  Events: /events
  Blog: /blog

links_projects:
  Project FUTURE: /
  ICPA-18 <span class="d-sm-none d-md-inline">conference</span>: https://www.bgsu.edu/icpa18.html
  IWZnO 2020 <span class="d-sm-none d-md-inline">conference</span>: http://physics.bgsu.edu/IWZnO_2020/

links_funding:
  National Science Foundation: http://www.nsf.gov/
  United States Air Force: http://www.airforce.com/

rss: /atom.xml

# Content
excerpt_link: Read More →
fancybox: true

# Sidebar
# sidebar: right
# widgets:
# - category
# - tag
# - tagcloud
# - archive
# - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

# Math Formulas Render Support
math:
  # Default (true) will load mathjax / katex script on demand.
  # That is it only render those page which has `mathjax: true` in Front-matter.
  # If you set it to false, it will load mathjax / katex srcipt EVERY PAGE.
  per_page: true

  # hexo-renderer-pandoc (or hexo-renderer-kramed) required for full MathJax support.
  mathjax:
    enable: true
    # See: https://mhchem.github.io/MathJax-mhchem/
    mhchem: false

  # hexo-renderer-markdown-it-plus (or hexo-renderer-markdown-it with markdown-it-katex plugin) required for full Katex support.
  katex:
    enable: false
    # See: https://github.com/KaTeX/KaTeX/tree/master/contrib/copy-tex
    copy_tex: false