# Header

logo: /images/selimlab-logo-vector-with-text.svg

slogan: Fundamental and applied research on wide band gap materials.<br />Radiation damage studies.

menu:
  Dr. <span class="d-inline d-sm-none d-xl-inline">Farida A.</span> Selim: /
  <span class="d-inline d-sm-none d-xl-inline">Research</span> Facilities: /facilities
  Publications: /publications
  Teaching: /teaching
  Software<span class="d-inline d-sm-none d-xl-inline"> Development</span>: /software
  People: /people
  Events: /events  
  Blog: /blog

menuFooter:
  Dr. Selim: /
  Facilities: /facilities
  Publications: /publications
  Research: /research
  Teaching: /teaching
  Software: /software
  People: /people
  Events: /events
  Blog: /blog

links_projects:
  Project FUTURE: https://www.lanl.gov/projects/future/index.php
  ICPA-18 <span class="d-sm-none d-md-inline">conference</span>: https://www.bgsu.edu/icpa18.html
  IWZnO 2020 <span class="d-sm-none d-md-inline">conference</span>: http://physics.bgsu.edu/IWZnO_2020/

links_funding:
  National Science Foundation: http://www.nsf.gov/
  United States Air Force: http://www.airforce.com/

rss: /atom.xml

# Content
excerpt_link: Read More →
fancybox: true

# Sidebar
# sidebar: right
# widgets:
# - category
# - tag
# - tagcloud
# - archive
# - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: